#  Build & Publish

image: node:lts-alpine3.15

definitions:
  steps:
    - step: &build
        name: Build
        caches:
          - node
        script:
          - npm install
          - npm run build
        artifacts: # defining the artifacts to be passed to each future step.
          - dist/**

pipelines:
  branches:
    develop:
      - step: *build
    master:
      - step: *build
      - step:
          name: Publish
          deployment: production
          image: atlassian/default-image:latest
          script:
            - npm version patch -m "Upgrade to %s [skip ci]"
            - git push && git push --tags
            - pipe: atlassian/npm-publish:0.3.2
              variables:
                NPM_TOKEN: $NPM_TOKEN
                # FOLDER: '<string>' # Optional.
                # EXTRA_ARGS: '<string>' # Optional.
                # NPM_REGISTRY_AUTH_URL: '<string>' # Optional.
                # DEBUG: '<boolean>' # Optional.