name: Publish Package to npmjs
on:
    release:
        branches: [main]
        types: [created]
    workflow_dispatch:
        branches: [main]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            # Setup .npmrc file to publish to npm
            - uses: actions/setup-node@v3
              with:
                  node-version: '16.x'
                  # Defaults to the user or organization that owns the workflow file
            - name: Setup .yarnrc.yml
              run: |
                  yarn config set npmScopes.@loom-js.npmRegistryServer "https://registry.npmjs.org"
                  yarn config set npmScopes.@loom-js.npmAlwaysAuth true
                  yarn config set npmScopes.@loom-js.npmAuthToken ${NPM_AUTH_TOKEN}
                  cat .yarnrc.yml
              env:
                  NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
            - name: Install dependencies
              run: yarn workspace @loom-js/core install
            - name: Publish
              run: yarn workspaces foreach --no-private npm publish
