name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    # To use Turborepo Remote Caching, set the following environment variables for the job.
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}

    steps:
      - name: Checkout Repo
        # https://github.com/actions/checkout
        uses: actions/checkout@v4

      - name: Cache turbo
        # https://github.com/actions/cache
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Install pnpm
        # https://github.com/pnpm/action-setup
        uses: pnpm/action-setup@v3

      - name: Install Node.js 20.x
        # https://github.com/actions/setup-node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        # https://github.com/changesets/action
        uses: changesets/action@v1
        with:
          # This expects you to have a script called publish-package which does a build for your packages and calls changeset publish
          publish: pnpm publish-packages
          # version: pnpm version-packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      # - name: Send a Slack notification if a publish happens
        # if: steps.changesets.outputs.published == 'true'
        # You can do something when a publish happens.
        # run: my-slack-bot send-notification --message "A new version of ${GITHUB_REPOSITORY} was published!"
